dist: trusty
branches:
  only:
    - develop
    - master
language: python
python:
  - "2.6"
  - "2.7"
before_install:
  - export PYTHONIOENCODING=UTF-8
  - wget -O /tmp/simplemedia.tar.gz https://github.com/vlmaksime/script.module.simplemedia/archive/master.tar.gz
  - tar -C /tmp -xf /tmp/simplemedia.tar.gz
  - ln -s /tmp/script.module.simplemedia-master/script.module.simplemedia/ script.module.simplemedia
install:
  - pip install codecov codacy-coverage future
  - pip install https://github.com/romanvm/script.module.simpleplugin/archive/develop.zip
  - pip install https://github.com/vlmaksime/script.module.simplemedia/archive/master.zip
  - pip install https://github.com/vlmaksime/Kodistubs/archive/develop.zip
script:
  - coverage run tests.py
after_success:
  - codecov
  - coverage xml
  - python-codacy-coverage -r coverage.xml
